services:
  - type: web
    name: my-flask-app
    env: python
    pythonVersion: "3.11.8"   # 👈 Use Python 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app  # 👈 Replace 'app:app' if your main file or Flask instance has a different name
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: your_secret_key_here
      - key: DATABASE_URL
        value: your_database_url_here
